Aiogram
Concert-Mate/Bot pull request #6
Opened 2024-04-10 10:42 UTC by Wooshey1411

2024-04-12 06:03 UTC, dura0ok requested changes, later dismissed

2024-04-12 06:03 UTC, dura0ok commented on main.py
> +    print('successful launch')
Давай откажемся от обычных принтов в сторону, скажем, [Loguru
](https://github.com/Delgan/loguru)Почему?
Потому что чтобы потом после откладки скажем не убирать, можно много уровней логирования
Переделать очень просто и быстро, но выгоды много!

2024-04-12 06:03 UTC, dura0ok commented on main.py
> +    print('successful launch')
А еще почему у тебя сразу здесь success еще до всего :skull:

2024-04-12 06:03 UTC, dura0ok commented on main.py
> +    logging.basicConfig(level=logging.INFO, stream=sys.stdout)
А вот увидел логгер, но лучше именно на логуру и убрать ваще принты

2024-04-12 06:03 UTC, dura0ok commented on src/api_service/api_methods.py
> +    INTERNAL_SERVER_ERROR = 3
INTENUM никак нельзя прикрутить?

2024-04-12 06:03 UTC, dura0ok commented on src/api_service/api_methods.py
> +    2: __get_user_registration_response,
это что за? 0_0

2024-04-12 06:03 UTC, dura0ok commented on src/api_service/api_methods.py
> +    3: __get_add_playlist_response,
Плюс оч много однотипного кода из-за этого как будто, надо чет подумать

2024-04-12 06:03 UTC, dura0ok commented on src/handlers/common_handlers.py
> +        print('Некорректный код')
Логи

2024-04-12 06:03 UTC, dura0ok commented on src/handlers/common_handlers.py
> +    except ValueError:
А что если другой эксепшен

2024-04-12 06:03 UTC, dura0ok commented on src/handlers/common_handlers.py
> +    user_id = message.from_user.id
Навесь тайпхинты на переменные
какого типа user_id?

2024-04-12 06:03 UTC, dura0ok commented on src/handlers/common_handlers.py
> +    if response.code == UserRegistrateCodes.SUCCESS:
Портянка ифов пугает
Предлагаю перейти на паттерн(Команды - как учил Савенко)
он тут как будто к месту

2024-04-12 06:03 UTC, dura0ok commented on src/handlers/registration_handlers.py
> +            response.code == AddCityCodes.INTERNAL_SERVER_ERROR or
ой емае
надо чет с этим сделать

2024-04-12 06:03 UTC, dura0ok commented on src/handlers/registration_handlers.py
> +            response.code == AddCityCodes.USER_NOT_FOUND or
страшно

2024-04-12 06:03 UTC, dura0ok commented on src/handlers/registration_handlers.py
> +            await __add_link(link, True, state)
пугает все в await
Вопрос нельзя ли точно что-то в корутинах запустить?

2024-04-12 06:03 UTC, dura0ok commented on src/keyboards/registration_keyboards.py
> +skip_add_cities_texts = ['Прекратить ввод городов']
Массив из одной строки 0_0

2024-04-12 06:07 UTC, dura0ok commented on src/handlers/registration_handlers.py
> +            await __add_link(link, True, state)
asyncion create task

2024-04-14 15:01 UTC, llirik42 requested changes, later dismissed

2024-04-14 15:01 UTC, llirik42 commented on main.py
> +    print('successful launch')
Про Loguru не слушай молодого человека. Сначала надо MVP сделать, а потом уже накручивать логирование через сторонний сервис. Переделать не очень просто)

Но да, всё-таки говорить об успешном запуске нужно после запуска, а не до!

2024-04-14 15:01 UTC, llirik42 commented on src/api_service/api_methods.py
> +    INTERNAL_SERVER_ERROR = 3
Лучше отнаследуй UserRegistrateCodes от `IntEnum` - это ни на что не повлияет, это лишь для эстетов

2024-04-14 15:01 UTC, llirik42 commented on src/api_service/api_methods.py
> +    2: __get_user_registration_response,
Вот это рил муть

2024-04-14 15:01 UTC, llirik42 commented on src/api_service/api_methods.py
> +    3: __get_add_playlist_response,
Согл

2024-04-14 15:01 UTC, llirik42 commented on src/handlers/common_handlers.py
> +    user_id = message.from_user.id
Поддерживаю

2024-04-14 15:01 UTC, llirik42 commented on src/handlers/common_handlers.py
> +    except ValueError:
И можно бы смотреть инфу про exception. Для этого используй `except ValueError as e`, и дальше можно будет обращаться через `e.`

2024-04-14 15:01 UTC, llirik42 commented on src/handlers/registration_handlers.py
> +            response.code == AddCityCodes.INTERNAL_SERVER_ERROR or
Можно попробовать использовать мапу с корутинами, и в зависимости от кода будет выполняться одна из них

2024-04-14 15:01 UTC, llirik42 commented on src/handlers/registration_handlers.py
> +            await __add_link(link, True, state)
Здесь нет смысла создавать корутины

2024-04-14 15:01 UTC, llirik42 commented on src/handlers/registration_handlers.py
> +            await __add_link(link, True, state)
Так что не слушай Стёпу

2024-04-16 16:38 UTC, merged